site_name: Roommate Docs
site_url: https://hoork.github.io/roommate
site_author: Hoork
site_description: Documentation for Roommate plugin

repo_name: hoork/roommate
repo_url: https://github.com/hoork/roommate

copyright: Copyright &copy; 2025 Kirill Rozhkov

theme:
  name: material
  features:
    - search.suggest
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  logo: assets/images/roommate_logo.png
  favicon: assets/images/roommate_logo.png
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - getting_started/core_concepts.md
    - getting_started/installation.md
    - getting_started/settings.md
  - Tutorials:
    - tutorials/create_rooms.md
    - tutorials/styles.md
    - tutorials/positioning.md
    - tutorials/surfaces.md
  - References:
    - references/selecting_blocks.md
    - references/selecting_parts.md
